### ISSUE TITLE
where to install this client npm ?

### ISSUE THREAD

**Issue by Vigneshent** [getcandy/nuxt-client#2]
I have configured hub and api successfully, working in client installation. where do we need to install this npm [inside api folder or hub one]

**Comment by glennjacobs** [comment]
Are you trying to make a NuxtJS storefront?

**Comment by Vigneshent** [comment]
yes, working in NuxtJS storefront, i have successfully installed api and hub[back-end] But dont know how to start with storefront, where to install this client npm

**Comment by glennjacobs** [comment]
The hub is a NuxtJS app and it uses this API client. I would check that as a reference. 

Check how it's added to the `package.json` file and also the `nuxt.config.js`. 

You can of course simply use Axios directly if you're more comfortable with that.

**Comment by Vigneshent** [comment]
ya, inside hub folder i have installed package and updated package.json and updated nuxt.config.js. How to run storefront ?

**Comment by Vigneshent** [comment]
My api running running in localhost:8000 and my hub running in localhost:3000, what is the url for storefront ?

**Comment by Vigneshent** [comment]
where to add this, file path ?

Config

{
  host: "http://store-api.test"
}

**Comment by glennjacobs** [comment]
Sorry, I'm confused. Are you trying to make a storefront, or did you think this was a storefront? Our storefront hasn't been released yet.

**Comment by Vigneshent** [comment]
I'm working in below package for storefront, is it not the store-front?

https://github.com/getcandy/nuxt-client

**Comment by glennjacobs** [comment]
No, that's simply the API client. Just a different way to use the API functions.

**Comment by Vigneshent** [comment]
oh ok thanks!
